language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
  - "14"
git:
  depth: 3
script:
  - yarn build
deploy:
  provider: script
  script: bash scripts/deploy.sh $FTP_HOST $FTP_USER $FTP_PASS
  on:
    branch: master
